### PR TITLE
refactor: exclude source files from npm package

### PR DESCRIPTION
**Pull request by lex111**

### CODE REVIEW

**Comment by yangshun** [comment]
The idea of including the source files in the published package is so that
if people want to use their own postcss config to bundle, they can. It's
similar to how Bootstrap includes their raw Sass files for people who want
to have more finegrain control over the output.e

**Comment by Josh-Cena** [comment]
PostCSS setup is quite hard to replicate, so I won't expect people to do that and produce output different from ours. Do we have benchmark about how much publish size this will save?

We do use PostCSS in Docusaurus, but only for RTL and autoprefixer...

**Comment by lex111** [comment]
It is doubtful that anyone uses these source files, alright, let's keep them then.

**Comment by slorber** [comment]
Also related to the proposal to rewrite to SCSS by @RDIL: https://github.com/facebookincubator/infima/issues/226

My personal opinion remains that having Infima/Docusaurus being separated increases the public API surface, adds dev friction, and makes it difficult to test changes in Infima + Docusaurus integration in an atomic way (single PR with deploy preview)... 

For me the less Infima internals we expose the better, but I'm not sure everyone agrees on that 🤷‍♂️

**Pull request closed without merging**
