### PR TITLE
fix: apply --ifm-heading-font-family to headings

### PR DESCRIPTION
**Pull request by dsmmcken**
Root variable was created but never actually assigned to the headers.

### CODE REVIEW

**Review by lex111 — COMMENTED** [review]
This is unnecessary because heading font is implicitly inherited from root element `html`, so let's remove that variable.

**Comment by dsmmcken** [comment]
It's extremely common to use a separate font-stack for headings vs body. This should be supported, Facebook themselves use "Optimistic Display" for headings and "Optimistic Text" for body on most corporate sites.

That's how I stumbled across this:
1. Went to set headings to a different brand related font for my site
2. Saw variable available to do so already on root
3. Set variable, saw no effect 😞 
4. Found variable is not applied to anything

**Comment by lex111** [comment]
I see, I'm fine with it, going to merge this.

**Review by lex111 — APPROVED** [review]

**Comment by lex111** [comment]
@dsmmcken thanks!

**Pull request merged**
