### PR TITLE
Alert / Admonition redesign

### PR DESCRIPTION
**Pull request by slorber**
Fix https://github.com/facebookincubator/infima/issues/55

## Changes

Redesign Infima alerts so that we can redesign Docusaurus admonitions:

- Reuse existing Infima colors
- Add new color variants `--ifm-color-$(color)-contrast background + `--ifm-color-$(color)-contrast-emphasis`
- Emphasis on background pass WCAG contrast tests with AAA
- Keep dark mode support
- Make it easy to customize alerts/admonitions through CSS variables
- Also redesign blockquotes to be consistent with alert design (and fix highly inaccessible contrast)
- Support for tabs

Not directly related:

- Simplify existing verbose color declaration with `@each`
- Apply missing `.clean-btn` class on Alert doc page, issue appearing after #150
- Add anchor links to Infima demo sections

## To review

- Alerts: https://deploy-preview-155--infima.netlify.app/demo/#alerts
- Alerts dark: https://deploy-preview-155--infima.netlify.app/demo/?dark=true#alerts
- Alerts in Docusaurus: https://deploy-preview-155--infima.netlify.app/docs/components/alert
- Quotes: https://deploy-preview-155--infima.netlify.app/demo/#typography
- Quotes dark: https://deploy-preview-155--infima.netlify.app/demo/?dark=true#typography

## Screenshots

Will try to keep them up-to-date with current code:

### Infima alerts

image

image

### Docusaurus admonitions

image

image

### Quotes

image

image

### CODE REVIEW

**Comment by HonkingGoose** [comment]
This looks way better than what we have now! 🚀 

I did notice 2 things though...

## Edge case fixed with new design?

Does the new design fix this edge-case?

> Another edge case admonitions redesign should take into account:
> 
> image

## X text/button to close alert lacks contrast

Lowest contrast score for the X text on colored backgrounds is `2.49:1` in the non-active state.

> **Check the contrast for all icons.**
>
> Level AA compliance requires a contrast ratio of 3.0:1.

https://www.a11yproject.com/checklist/#color-contrast

**Steps to reproduce:**

1. Use latest Firefox browser
2. Open the preview https://deploy-preview-155--infima.netlify.app/demo/#alerts
3. Turn on developer toolbar with <kbd>F12</kbd>
4. Use the accessibility picker to hover over the X text of the alert
5. See contrast check fails AA contrast checks for the X text on all alerts

Chrome probably also has a accessibility tab with tools to detect the contrast of a element.

**Comment by slorber** [comment]
Thanks @HonkingGoose , that should be better now. Also added the tabs in alerts edge case to the demo page

**Comment by HonkingGoose** [comment]
> Thanks @HonkingGoose , these should be better now.

The close button is way more visible now! 😄

> Added the tabs in alerts edge case to the demo page and screenshots.

The alert component with tabs in them don't have a close button **X**, is that intended behavior?

**Comment by slorber** [comment]
@HonkingGoose not intended but not important. The close button is optional and Docusaurus doesn't even use it.

**Comment by HonkingGoose** [comment]
> Added a little hover effect on links, not very visible through but can't make it more visible without a lower contrast ratio, so it seems better to keep the link text readable.

That hover effect is _very_ subtle. I think it needs to be a lot clearer. 😉 

Is it an option to make the link text a bit bolder when you hover over it?
Something like this, but in Infima:

```css
a:hover {
  font-weight: 700;// bold
}
```

**Comment by slorber** [comment]
> Is it an option to make the link text a bit bolder when you hover over it?

Not a good idea because link width will increase and this triggers potential layout changes on the alert (could create new lines)

I don't have much ideas how to make it more visible, because using a darker/lighter color is not very visible. Some things remain possible, like using `text-shadow`...

**Comment by HonkingGoose** [comment]
> Some things remain possible, like using `text-shadow`...

I tried adding `text-shadow` to `a` tags in the browser, and it looks bad, and makes the text harder to read. 😞 

---

I did try this in the browser, which looks nice:

```css
a:hover {
  text-decoration-thickness: 2px,
}
```

But this is probably also a bad idea, because of possible layout shifts?

**Comment by slorber** [comment]
Thanks, will take a look at that solution.

Using link opacity is not too great for text selection, as @Simek mentioned, so I'd rather find another way:

image

**Comment by slorber** [comment]
Seems to work fine. Not perfect but a good enough solution.

Which is better?

image

image

**Comment by HonkingGoose** [comment]
> Which is better, on link :hover ?
> 
> image
> 
> image

I like the bottom variant the best, as it uses a dark hue of the background color. This way it feels like the underline belongs to the component.

**Comment by slorber** [comment]
> I like the bottom variant the best, as it uses a dark hue of the background color. This way it feels like the underline belongs to the component.

Let's test this then, not too hard to revert if people disagree

---

@lex111 @yangshun I don't like too much having this inline code block horizontal padding, as it breaks the link underline and separates too much the word from the rest.

image

Going to reduce it, let me know if that's a problem:

image

**Pull request merged**
